---
title: "Equations for affinity based drug delivery from cylyndrical polymers"
output: html_notebook
---


# Equations for Drug Release

Release from affinity polymer disks can be modeled as described by Andrew Fu. [@Fu:2011cj]. 



In the next set of equations the continuous equation will be given followed by the
discretized version used to solve it with the method of lines. 

The spatial derivative is discretized as given

$$ \Delta = \frac{1}{N}, z_{i}^{*} = i\Delta \\
z^{*} = \frac{z}{\delta}\\
(i = 0,1,2,...,N) $$

The rate of binding within the hydrogel is given by

$$ R_b = \bigg[\frac{k_1C_0} {k_2}\bigg] C_L\bigg(\bigg[\frac{C_T}{C_0}\bigg]-C_{L-C}\bigg)-C_{L-C} \\
R_{b,i}= P_1C_{L,i}\bigg(P_3-C_{L-C,i}\bigg)-C_{L-C,i}$$ 

Free drug in hydrogel varies according to

$$\frac {\partial C_L}{\partial \tau} = \bigg[ \frac {D}{k_2 \delta^2} \bigg ]\frac{\partial^2C_L}{\partial z^2}-R_b  \\
\frac{dC_{L,i}}{d\tau} = P_2 \frac{C_{L,i+1}+2C_{L,i}+C_{L,i-1}}{\Delta^2}-R_{b,i} \\
(i = 1,2, ..., N-1 )$$


Drug to cyclodextrin complex varies according to

$$\frac {\partial C_{L-C}} {\partial \tau} = R_b \\
\frac{\partial C_{L-C}} {\partial \tau} = R_{b,i} \\
(i = 1,2, ..., N-1 )$$

With dimensionless boundary conditions at the center of the hydrogel given by

$$z = 0 , \frac {\partial C_L}{\partial z} = 0 \\
i = 0: \frac{\partial C_{L,0}}{\partial z} = 0 $$
For the release phase the dimensionless initial conditions are given by

$$ \tau = 0, C_L = \frac {C_L^{eq}} {C_0}, C_{L-C} = \frac {C_L^{eq}}{C_0} $$
which are the same initial conditions for the discretized version.

Conditions at the boundary of the hydrogel and drug release solution 

$$\tau = 0, z = 1, C_L = 0 \\
\tau = 0, i = 1: C_{L,N}=0$$

The rate of release is given by the following equation
$$\frac {dM_R} {d \tau} = - \frac {1}{2} \bigg[\frac{D} {k_2 \delta^2}\bigg] \frac {\partial C_l}{\partial z} \\ 
\frac {dM_R} {d \tau}=-\frac{1}{2}P_2\frac{C_{L,N}-C_{L,N-1}}{\Delta}$$


And with initial conditions given by:

$$M_R = 0, \tau = 0$$
The model is rendered dimensionless as it follows
$$ P_1 = \bigg[\frac{K_1*C_0}{K_2}\bigg], P_2 = \bigg[\frac{D}{K_2\delta^2}\bigg], P_3 = \bigg[\frac{C_T}{C_0}\bigg]$$


